# Authentication

# Mohib Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA
# Zahin Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJ6YWhpbiIsIm5iZiI6MTY5MDA4NzMyMCwiZXhwIjoxNjkwNjkyMTIwLCJpYXQiOjE2OTAwODczMjB9.i0bQViYHPLvVkycCrswKRTlvFtw5krTLFVwIrv1wTDYLvwqgmLg4NrgTT5pyEIKFWX3qXFjer4KNV_wdyiV5Sw
POST http://localhost:5168/api/authentication/register
Content-Type: application/json

{
    "userName": "zahin",
    "password": "Pa$$w0rd"
}

###

POST http://localhost:5168/api/authentication/login
Content-Type: application/json

{
    "userName": "mohib",
    "password": "Pa$$w0rd"
}


###

# Friend Request
GET http://localhost:5168/api/friendRequests
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA

###

POST http://localhost:5168/api/friendRequests?requestToUserId=2
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA

###

POST http://localhost:5168/api/friendRequests/accept/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA

###

DELETE  http://localhost:5168/api/friendRequests/4
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA

###
# Friend
GET http://localhost:5168/api/friends
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJtb2hpYiIsIm5iZiI6MTY5MDA4NzMwMSwiZXhwIjoxNjkwNjkyMTAxLCJpYXQiOjE2OTAwODczMDF9.-FF3x7yEF89Z9RA213aE5xap4FvCKsnKLYUwSiOivPzDfd0vDpKRCWiKNVKfnWTMyP0JoOBaidjYlT_dzvABMA


###

